---

- name: install sshguard
  package:
    name: '{{ sshguard_packages }}'
    state: 'present'
  register: t_sshguard_install

- name: setup sshguard directory tree
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: "{{ sshguard_dir }}", owner: root, group: "{{ root_group }}", mode: "0755" }
    - { path: "{{ sshguard_conf_dir }}", owner: clamav, group: "{{ root_group }}", mode: "0755" }
    - { path: "{{ sshguard_run_dir }}", owner: root, group: "{{ root_group }}", mode: "0755" }
    - { path: "{{ sshguard_db_dir }}", owner: clamav, group: "{{ root_group }}", mode: "0755" }

- name: configure sshguard
  template:
    src: sshguard/sshguard.conf
    dest: "{{ sshguard_conf_dir }}/{{ sshguard_conf_file }}"
    owner: root
    group: "{{ root_group }}"
    mode: '0644'
  register: t_sshguard_config


- name: configure service for daemontools
  block:
    - name: stop base services
      block:
        - service:
            name: "{{ sshguard_service }}"
            state: stopped

        - include: sysrc.yml key="{{ sshguard_service }}_enable" value="NO"

    - name: deploy svscan scripts
      block:
        - file:
            path: "{{ item.path }}"
            owner: root
            group: "{{ root_group }}"
            mode: "{{ item.mode }}"
            state: directory
          loop:
            - { path: "{{ sshguard_conf_alt_dir }}", owner: root, group: "{{ root_group }}", mode: "0755" }
            - { path: "{{ sshguard_svscan_dir }}", owner: root, group: "{{ root_group }}", mode: "0755" }
            - { path: "{{ sshguard_svscan_dir }}/log", owner: root, group: "{{ root_group }}", mode: "0755" }

        - file:
            src: "{{ sshguard_conf_dir }}/{{ sshguard_conf_file }}"
            dest: "{{ sshguard_conf_alt_dir }}/{{ sshguard_conf_file }}"
            state: link


        - template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: root
            group: "{{ root_group }}"
            mode: "{{ item.mode }}"
          loop:
            - { src: sshguard/svscan/run, dest: "{{ sshguard_svscan_dir }}/run", mode: "0755" }
            - { src: sshguard/svscan/log/run, dest: "{{ sshguard_svscan_dir }}/log/run", mode: "0755" }

    - name: link svscan
      file:
        src: "{{ sshguard_svscan_dir }}"
        dest: "{{ daemontools_svscan_dir }}/supervised/sshguard"
        state: link

  when: has_daemontools


- name: configure service for FreeBSD
  block:
    - include: sysrc.yml key="{{ sshguard_service }}_enable" value="YES"

    - service:
        name: "{{ sshguard_service }}"
        state: started
      register: t_sshguard_service

    - service:
        name: "{{ sshguard_service }}"
        state: restarted
      when: t_sshguard_config.changed and not t_sshguard_service.changed
  when: ansible_distribution == 'FreeBSD' and not has_daemontools

- name: set has_sshguard
  set_fact:
    has_sshguard: true
