---

- name: sshguard
  when: want_sshguard
  block:
    - include_tasks: context.yml

    - include_tasks: sshguard.yml


- name: set has_sshguard
  set_fact:
    has_sshguard: "{{ want_sshguard }}"
